### ISSUE TITLE
help with getting token.

### ISSUE THREAD

**Issue by shaunie2fly** [dkatavic/onedrive-api#23]
Hi
THis may be a dumb question but im struggling to get a valid token.

I setup an app registration in app registrations. use the cleint ID and key and send a request to https://login.microsoftonline.com/common/oauth2/v2.0/token'; to generate a token.  I use the token for a request in the onedrive-api and get this response.

{ code: 'BadRequest',
        message:
         'Current authenticated context is not valid for this request. This occurs when a request is made to an endpoint that requires user sign-in. For example, /me requires a signed-in user.  Acquire a token on behalf of a user to make requests to these endpoints.  Use  the OAuth 2.0 authorization code flow for mobile and native apps and the OAuth 2.0 implicit flow for single-page web apps.',

Please can you give me a direction to go to troubleshoot further?

Regards
Shaun

**Comment by dkatavic** [comment]
Hey @shaunie2fly 

You will need to acquire a token on behalf of the user. Try following this page and let me know did it work https://docs.microsoft.com/en-us/graph/auth-v2-user

**Comment by theraw** [comment]
@dkatavic can you share a wiki on how to actually create access token?! because as far as i've been testing with 
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=xxxx&response_type=code&redirect_uri=https://github.com&response_mode=query&scope=onedrive.readwrite%20user.read%20mail.read%20offline_access&state=12345
```

all what i get from this is ERROR `401`
```js
StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'StatusCodeError',
  statusCode: 401,
  message: '401 - [object Object]',
  error: {
    error: {
      code: 'InvalidAuthenticationToken',
      message: 'CompactToken parsing failed with error code: 80049217',
      innerError: [Object]
    }
  },
  options: {
    method: 'POST',
    uri: 'https://graph.microsoft.com/v1.0/me/drive/items/root/children',
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'Bearer Mb4xxxxxxxxxxxxxxxxxxxx10aa'
    },
    body: { name: 'Folder name', folder: {} },
    json: true,
    callback: undefined,
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false
  },
```

**Comment by dkatavic** [comment]
@theraw I haven't had that type of error before. Are you using OneDrive for Bussiness? Can you generate token using graph explorer and try it out in your code https://developer.microsoft.com/en-us/graph/graph-explorer/preview ?

**Comment by theraw** [comment]
i tried and it works on browser
![image](https://user-images.githubusercontent.com/32969774/81501626-b1fe1a00-92d9-11ea-8751-f09b672e4eb0.png)
i copy paste that token and tried to use got this erro
```js
StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'StatusCodeError',
  statusCode: 401,
  message: '401 - [object Object]',
  error: {
    error: {
      code: 'unauthenticated',
      message: "Must be authenticated to use '/drive' syntax",
      innerError: [Object]
    }
  },
  options: {
    method: 'POST',
    uri: 'https://graph.microsoft.com/v1.0/me/drive/items/root/children',
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'Bearer EwBgA8l6BAAUO9chh8cJscQLmU+LSxxxxxxxxx
...
```

` uri: 'https://graph.microsoft.com/v1.0/me/drive/items/root/children',`

i tried to create a folder from https://developer.microsoft.com/en-us/graph/graph-explorer/preview
and url for api 1.0 was `https://graph.microsoft.com/v1.0/me/drive/root/children`
so i tried to remove "`items`" that you have on https://github.com/dkatavic/onedrive-api/blob/master/lib/items/createFolder.js#L31
and execute request again but error is the same `Must be authenticated to use '/drive' syntax`

i think i should create the token by my app and i tried creating a new app
```
https://login.microsoftonline.com/a0ccfeebxxxxxx3e7345/oauth2/v2.0/authorize?client_id=035eb1axxxxxxxx-edfbd76daace&redirect_uri=https://example.com&response_type=code&scope=offline_access%20files.read%20files.read.all%20files.readwrite%20files.readwrite.all&state=12345
```
this forwarded me to 
```
https://example.com/?code=OAQABAAIAAAAm-06blBE1TpVMil8KPQ41CSCdqoRURg0Hnk0sPD5ESOaZkeOlQ8q0zQYbwcOpMM9pvdI_aSqywlnvlhXlaIFnktWVfblbFHnaIRhRWasPc3vXdrzZMK6VpRTPaIVhfiYX04z1YpIYo9W02psq8_tJhGAdIxwMhsz32Gta4edS_Li4RHpCDiWGZBeCuKKDAa2QClKUq0sMBs2haFNmkufHHj5je_YMvo1LH52j9AEg_WHTQY9YSgv1gVVKNcZqwTpqUkOWEZ8SsjKJX5gi4tkbxLcPxUrlSVJvpnqk3R1hgXCOb0aDPHU36eo4eSCPOppDwhIrw7uaVhqtrDe8OTlZu75fPdK2tLfawauD0X1T_MsGFb25U3ClwALYAgLB-3bgYgPlyxxxxxxxxxxxxxxxxxgOq_Ga8wMAGlPiXXjHXKlMZMqALOP6VV_0tgSlpd-QzloHlrMqhnek3AkxxxxxxxxxxxxxxxxxKaRZ1y06tLvSqy95gh0krhs7PrjrVZNaaNnIrUTZ0cBfMIP9a0IqmAzVzzsD0q5mb5JZP08M2VwWgMWhB5f35zJl0qqBX8Bm804gnk7kxxxxxxxxxxxxxx12345&session_state=bd266de3-32a9-4xxxxxxxx9f0151
```
now i got this `OAQABAAIAAAAm...` and used it as accessToken on your nodejs pr and i'm getting 
```
root@DOPE-PC:/mnt/c/Users/RAW/Desktop/onedrive# node index.js
StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/mnt/c/Users/RAW/Desktop/onedrive/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'StatusCodeError',
  statusCode: 401,
  message: '401 - [object Object]',
  error: {
    error: {
      code: 'InvalidAuthenticationToken',
      message: 'CompactToken parsing failed with error code: 80049217',
      innerError: [Object]
    }
  },
  options: {
    method: 'POST',
    uri: 'https://graph.microsoft.com/v1.0/me/drive/items/root/children',
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'Bearer OAQABAAIAAAAm
``` 

as you can see from first scr my account is not business

**Comment by theraw** [comment]
@dkatavic maybe there's some step i'm missing or doing wrong?

**Comment by theraw** [comment]
i had
`&response_type=code`
changed it to 
`&response_type=token`

got 
```
https://dopemovie.io/#access_token=eyJ0eXAiOiJKV1QiLCJub25jZxxxxxxxxxxxxxxxSfW7M-2QDIMUfE9A&token_type=Bearer&expires_in=3599&scope=Files.Read+Files.Read.All+Files.ReadWrite+Files.ReadWrite.All+profile+openid+email&state=12345&session_state=bd266de3-xxxxxxxxxxxxbc419f0151
```

tried executing nodejs with this token and got a new error `400`
```
message: 'Tenant does not have a SPO license.',
```
😕
