### ISSUE TITLE
'Authentication failed' | Unhandled rejection StatusCodeError: 401 - [object Object]

### ISSUE THREAD

**Issue by mirkomilova10** [dkatavic/onedrive-api#5]
So i was trying to use this API wrapper for a personal project and i needed to interact with OneDrive files, only problem that i keep getting this error message
```
Unhandled rejection StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/root/CloudRAID/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/root/CloudRAID/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/root/CloudRAID/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/CloudRAID/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/CloudRAID/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

And catching the error gives a long log in witch i found this
```
...
name: 'StatusCodeError',
  statusCode: 401,
  message: '401 - [object Object]',
  error: { error: { code: 'unauthenticated', message: 'Authentication failed' } },
  options: 
   { method: 'GET',
     uri: 'https://api.onedrive.com/v1.0/drive/items/root/children',
     headers: 
      { 'Content-Type': 'application/json',
...
```

I know the project hasn't been update since a year and maybe OneDrive's API has changed too since, but it's the only API for OneDrive on npm so i gave it a shot anyway
Hoping i can get some help

**Comment by mirkomilova10** [comment]
Found the issue: was using the wrong API endpoint
Switched the default one with `https://graph.microsoft.com/v1.0/drive/` since i'm using Microsoft Graph for authentication

**Comment by dkatavic** [comment]
@mirkomilova10 thanks for reporting and the explanation. I will check oneDrive updates and try to support `graph.microsoft.com`

**Comment by mirkomilova10** [comment]
I'm also working on implementing the upload API with upload sessions since the normal one only supports 4mb files trought PUT. I'll open a pull request if that's ok

**Comment by dkatavic** [comment]
Sure, all PRs are welcome :)
