### ISSUE TITLE
Dowloading several files 

### ISSUE THREAD

**Issue by venkas01** [dkatavic/onedrive-api#55]
Hi ,

Downloading several files as script , i get the below error. is the timeout on onedrive side or script side ?
Any parameters to overcome ..?

Please advise.

events.js:352
      throw er; // Unhandled 'error' event
      ^

RequestError: connect ETIMEDOUT 20.190.169.24:443
    at ClientRequest.<anonymous> (C:\onedrive\node_modules\got\dist\source\core\index.js:959:25)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:387:35)
    at ClientRequest.origin.emit (C:\\onedrive\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
Emitted 'error' event on Request instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1642074390106,
    socket: 1642074390138,
    lookup: 1642074390147,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1642074411185,
    abort: undefined,
    phases: {
      wait: 32,
      dns: 9,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 21079
    }
  }
}

**Comment by dkatavic** [comment]
Hi @venkas01 , as
```
firstByte: undefined,
download: undefined,
```
I would say that this is a network issue, probably you can't reach `20.190.169.24:443` . You should resolve it on network level. If you ping the same address it should not be able to reach the server
