### ISSUE TITLE
Problem with download

### ISSUE THREAD

**Issue by MikeNaso** [dkatavic/onedrive-api#59]
I tried to download a file and I got this error, I copied the example only different I added the right itemid
I am able to list the file with the same token

node:events:491
      throw er; // Unhandled 'error' event
      ^

HTTPError: Response code 401 (Unauthorized)
    at Request._onResponseBase (/Users/XXXXXX/node_modules/got/dist/source/core/index.js:905:31)
    at Request._onResponse (/Users/XXXXXX/node_modules/got/dist/source/core/index.js:940:24)
    at ClientRequest.<anonymous> (/Users/XXXXXX/node_modules/got/dist/source/core/index.js:954:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/Users/XXXXXX/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
Emitted 'error' event on Request instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1670752196547,
    socket: 1670752196548,
    lookup: 1670752196622,
    connect: 1670752196658,
    secureConnect: 1670752196780,
    upload: 1670752196780,
    response: 1670752196907,
    end: 1670752196926,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 74,
      tcp: 36,
      tls: 122,
      request: 0,
      firstByte: 127,
      download: 19,
      total: 379
    }
  }
}

However, using postman with the same URI and the same token I am able to download the file

I am new on node, probably I did something wrong

**Comment by namdien177** [comment]
I believe this issue is resolved. Please re-open if you are having any problems.
